### ISSUE TITLE
support RPC?

### ISSUE THREAD

**Issue by avijxiong** [developeranaz/Aria2-Rclone-Remote-Uploader-HEROKU#5]
i want to use AriaNg webui to connect app,

**Comment by developeranaz** [comment]
> i want to use AriaNg webui to connect app,

I tried and couldn't do it.
Because of heroku limitations.
I've also found, in another repository, that using aria2ng with rclone via heroku will cause the heroku account to be suspended.

**Comment by avijxiong** [comment]
> > i want to use AriaNg webui to connect app,
> 
> I tried and couldn't do it.
> Because of heroku limitations.
> I've also found, in another repository, that using aria2ng with rclone via heroku will cause the heroku account to be suspended.

thanks you for this repository
and the another repository will ban the account
