### ISSUE TITLE
Magnet download

### ISSUE THREAD

**Issue by 4o4n00b** [developeranaz/Aria2-Rclone-Remote-Uploader-HEROKU#9]
When I use magnet to download, it always reports an error:
![图片](https://user-images.githubusercontent.com/85382711/133034656-f8fca489-2d2f-491b-883a-9c5e91aa7f75.png)

**Comment by developeranaz** [comment]
For torrent uploads please use [this beta](https://github.com/developeranaz/Aria2-Rclone-URL-Uploader-HEROKU-Beta) 
and If your magnet link has good seeders it will download without any error.
